### ISSUE TITLE
formatting: pretty "Please" does not look good in all terminals 

### ISSUE THREAD

**Issue by bnb** [boneskull/buggin#2]
Testing the PR in good-first-issue, and it seems that the pretty "Please" font does not necessarily render well in all terminals:

![image](https://user-images.githubusercontent.com/502396/70407754-5661f480-19fa-11ea-8813-0c83edbaee4a.png)

**Comment by boneskull** [comment]
hmm, interesting.  What terminal are you using, out of curiosity?

**Comment by bnb** [comment]
The one in VS Code. I'm also using [Cascadia Code](https://github.com/microsoft/cascadia-code) as my font, which AFAIK doesn't have an italic option at the moment (https://github.com/microsoft/cascadia-code/issues/63).

**Comment by boneskull** [comment]
I'm changing the output in #4 so it doesn't use italics by default, but--_apologies_--if it were _me_, I'd probably use a more full-featured terminal font.  I don't _think_ that's VSCode's fault, but might be a combination of the two.
