### ISSUE TITLE
formatting: add additional line break before report link block

### ISSUE THREAD

**Issue by bnb** [boneskull/buggin#3]
In some cases the line that will read `Please report the issue at: [...]` can get extraordinarily large:

![image](https://user-images.githubusercontent.com/502396/70407877-ed2eb100-19fa-11ea-8ffa-146451c824fc.png)

As someone with dyslexia, there's a metric crapload of characters that are incredibly hard to read there - I can't immediately tell there are two distinct lines with different purposes here.

As such, it would be super helpful if there was a newline between the lines that read `The following {error type} is likely a bug in {project}` and `Please report the issue at: {issue link}`. This area of the code can be found [here](https://github.com/boneskull/buggin/blob/master/src/index.js#L135-L138).

**Comment by boneskull** [comment]
sure thing.  in #1 I'm working on user-defined templates, which will essentially solve both of your issues.

**Comment by boneskull** [comment]
I've implemented this in #4 as well (by default) but can otherwise be changed in a custom message
